# Utiliser l'image officielle de Java (OpenJDK 17 par exemple)
FROM openjdk:17-jdk-slim

# Ajouter le fichier JAR de l'application dans le conteneur
COPY target/my-spring-boot-app.jar app.jar

# Exposer le port 8080 pour l'application
EXPOSE 8080

# Démarrer l'application Spring Boot
ENTRYPOINT ["java", "-jar", "/app.jar"]
